# Site settings
title: John Teske
description: "Front-end and HTML Email Developer"
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more-->

social:
  - title: email
    url: "mailto:john.teske@gmail.com" #"mailto:john@johnteske.io"
  - title: Github
    url: "https://github.com/johnteske"
  - title: LinkedIn
    url: "https://www.linkedin.com/in/johndteske"

about: "Front-end Developer"
